PP-2~PP-6 automation
yang-yp/ppmoneyE2e pull request #3
Opened 2018-07-03 15:34 UTC by yang-yp

test/firstpage.js：new file。case （PP-4，PP-5，PP-6） add
test/login.js：case（ PP-2，PP-3 ）add

2018-07-04 04:41 UTC, darrenlau86 requested changes
please incorporate review feedback

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +describe(" a case of longin secess",function (){
这个脚本更像是一个global navigation的用例。Describe 需清晰概括此用例集的真正意图。以便在看测试报告时，一目了然。
可以改为：Verify global navigation of PPmoney

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +        var money =element(by.css('div.login-box-bd > div.user-data.cf > div.data-box.fl > label'));
请在根目录下创建test-framework/pages文件夹，创建home-page.js.
将25-33，以及下面的51-58， 77-85行的元素定义，提取到home-page.js中。
然后在本文件中调用。定义方式参考之前发你的我们的脚本。

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +        longOut.click();
不用在每个用例中都登录登出一遍，可以把line24，34-37 行提取到beforeAll中。
71行，提取到AfterAll中。
测试开始login一遍，中间进行各种测试，测试完成，logout一遍

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +/**
文件名需要精确概括本用例集意图。firstpage似乎不太清楚，这样的文件名多了以后，就乱了

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +    it("goto home page",function(done){
用例意图更像是再测试验证用户可以登录成功。可以改成：verify user can login success.
it里面多用表明意图的词汇：sb **can** do sth, sth **should** be sth.

2018-07-04 04:41 UTC, darrenlau86 commented on test/login.js
> +        var longOut =element(by.css('ul#topLoginState.site-nav-r.fr > li.menu.fr > a'));
一样的，提取元素至页面文件

2018-07-04 04:41 UTC, darrenlau86 commented on test/login.js
> +        userName.sendKeys("13718281997");
应该覆盖特殊字符，必填项验证， 空字符串，长字串的验证。

2018-07-04 04:41 UTC, darrenlau86 commented on test/login.js
> +        var loginWar = element(by.css('form#formLogin.login-bd > div.warning'));
定义元素时，元素名称最好体现出类型，比如loginBtn,usernameInput.
loginWar这种写法不推荐， war不是warning的简写，可以命名为：loingErrorMsg

2018-07-04 04:41 UTC, darrenlau86 commented on test/firstpage.js
> +        //var recharge =element(by.css('div.login-box-bd > div.user-data.cf > div.fl > a'));
pls remove useless comment

2018-07-09 14:40 UTC, yang-yp commented on test/firstpage.js
> +describe(" a case of longin secess",function (){
已经改了

2018-07-09 14:41 UTC, yang-yp commented on test/firstpage.js
> +        var money =element(by.css('div.login-box-bd > div.user-data.cf > div.data-box.fl > label'));
提到了home-page里

2018-07-09 14:41 UTC, yang-yp commented on test/firstpage.js
> +        longOut.click();
提到了beforeAll里

2018-07-09 14:41 UTC, yang-yp commented on test/firstpage.js
> +/**
文件名改成了actionOnHomepage

2018-07-09 14:41 UTC, yang-yp commented on test/firstpage.js
> +    it("goto home page",function(done){
改好了

2018-07-09 14:41 UTC, yang-yp commented on test/login.js
> +        var longOut =element(by.css('ul#topLoginState.site-nav-r.fr > li.menu.fr > a'));
提到了页面文件里

2018-07-09 14:41 UTC, yang-yp commented on test/login.js
> +        var loginWar = element(by.css('form#formLogin.login-bd > div.warning'));
改成了loginWarMsg

2018-07-09 14:42 UTC, yang-yp commented on test/firstpage.js
> +        //var recharge =element(by.css('div.login-box-bd > div.user-data.cf > div.fl > a'));
没用的都删掉了

2018-07-09 14:42 UTC, yang-yp commented on test/login.js
> +        userName.sendKeys("13718281997");
因为没写相应的case，这个还没做

2018-07-10 13:48 UTC, darrenlau86 commented on test/actionOnHomepage.js
> +        };
line 30-32 应该在line 25行后面。

2018-07-10 13:51 UTC, darrenlau86 commented on test/actionOnHomepage.js
> +/**
文件名貌似不太合适。global_navigation.js
best practice 是可以多用-或_     这样一眼就能看明白这个文件的用途。

2018-07-10 13:52 UTC, darrenlau86 commented on test/actionOnHomepage.js
> +        var closePopup = element(by.id('popbtn'));
此元素也放到页面文件中

2018-07-10 13:54 UTC, darrenlau86 requested changes
如果碰到脚本问题，需要先阅读脚本。
读代码的测试流，一句一句慢慢来，是不是跟实际相符。

2018-07-10 14:20 UTC, yang-yp commented on test/actionOnHomepage.js
> +/**
好，有点词穷了

2018-07-10 14:21 UTC, yang-yp commented on test/actionOnHomepage.js
> +        };
哦，尽然没想到！

2018-07-10 14:21 UTC, yang-yp commented on test/actionOnHomepage.js
> +        var closePopup = element(by.id('popbtn'));
OK

2018-07-14 10:14 UTC, darrenlau86 commented
@yang-yp  我帮你解决了一下你遇到的问题。
有些错误比如：expect(homePage.openAccountBtn.isDisplayed).toBe(true); //应该为isDisplayed()
还有找不到按钮是因为没在同一个page上，需要切换tab，帮你加了一个切换tab页的api。

做这种自动化测试总结出的经验：
1. 要仔细审查脚本步骤，一步一步走，如果哪里出现错误，就手动模拟一下脚本动作。一定要仔细观察，因为有些是特别小的细节
2. 重构，将复用性高的代码块提取到公共区域。一般用过两次或以上就要考虑提取。比如我加的switchTab
3. 页面动作有时需要加到element factory里面（e.g. homePage.js）， 因为有些需要等待，这样做就把等待的代码提取了，点击直接调用，而不用每次都写等待语句。
4. 我帮你解决问题是直接告诉你答案，但你需要的是寻找答案的能力，那样更深刻更牢固。所以我以后尽量只提示方法，解决问题你自己来
5. 多写脚本，多push，增加我们push -> review -> feedback -> update -> push的次数。像写作文一样，每次修改都会有进步。

2018-07-14 10:14 UTC, darrenlau86 commented
更新一下你的本地分支能看到我的修改

2018-07-14 10:16 UTC, darrenlau86 commented on test-framework/pages/homePage.js
> +HomePage.prototype.logOutBtn =element(by.css('ul#topLoginState.site-nav-r.fr > li.menu.fr > a'));
代码格式
=element 应该为：= element

2018-07-14 10:18 UTC, darrenlau86 commented on properties/application.js
> +  userNum:"注册号：1077513746487"
这里只需要将1077513746487 放在常量里。

2018-07-14 10:20 UTC, darrenlau86 commented on test/actionOnHomepage.js
> +        expect(homePage.loginOkLable.valueOf('注册号：1077513746487'));
这个expect语句貌似没写全，后面应该有个.toBe什么或者toContain什么
example: 
expect(managePage.appStatus.getText()).toEqual('Approval Pending');

2018-07-14 10:21 UTC, darrenlau86 commented on test/login.js
> +        expect(homePage.loginWarMsg.valueOf('帐号密码不匹配'));
没用过valueOf，感觉不太对。你要是确定就是算了

2018-07-14 16:06 UTC, yang-yp commented on test-framework/pages/homePage.js
> +HomePage.prototype.logOutBtn =element(by.css('ul#topLoginState.site-nav-r.fr > li.menu.fr > a'));
加上空格了

2018-07-14 16:06 UTC, yang-yp commented on properties/application.js
> +  userNum:"注册号：1077513746487"
为什么？

2018-07-14 16:07 UTC, yang-yp commented on test/actionOnHomepage.js
> +        expect(homePage.loginOkLable.valueOf('注册号：1077513746487'));
是写错了（为什么没有报错？！）。改成下面那样通过了

2018-07-14 16:07 UTC, yang-yp commented on test/login.js
> +        expect(homePage.loginWarMsg.valueOf('帐号密码不匹配'));
不确定，好像不对，改了

2018-07-14 16:12 UTC, yang-yp commented
switchBrowserTabs 是指切换浏览器的窗口吗？tabIndex 是怎么订的？默认吗？我pull了，测了一下pp-5,pp-6还是没有pass

2018-07-26 16:08 UTC, closed without merging